# Ports of Arrival in India
from datetime import datetime, timezone, timedelta

_IST = timezone(timedelta(hours=5, minutes=30))

def now_ist() -> datetime:
    """Return current naive datetime in IST (UTC+05:30)."""
    return datetime.now(_IST).replace(tzinfo=None)

PORTS_OF_ARRIVAL = [
    "Agatti Seaport",
    "Ahmedabad Airport",
    "Amritsar Airport",
    "Bagdogra Airport",
    "Bengaluru Airport",
    "Bhubaneshwar Airport",
    "Calicut Airport",
    "Calicut Seaport",
    "Chandigarh Airport",
    "Chennai Airport",
    "Chennai Seaport",
    "Cochin Airport",
    "Cochin Seaport",
    "Coimbatore Airport",
    "Darranga Landport",
    "Delhi Airport",
    "Gaya Airport",
    "Goa Airport (Dabolim)",
    "Goa Airport (Mopa)",
    "Goa Seaport",
    "Guwahati Airport",
    "Hyderabad Airport",
    "Indore Airport",
    "Jaipur Airport",
    "Jogbani Landport",
    "Kamarajar Seaport",
    "Kandla Seaport",
    "Kannur Airport",
    "Kattupali Seaport",
    "Kolkata Airport",
    "Kolkata Seaport",
    "Kollam Seaport",
    "Lucknow Airport",
    "Madurai Airport",
    "Mangalore Airport",
    "Mangalore Seaport",
    "Mumbai Airport",
    "Mumbai Seaport",
    "Mundra Seaport",
    "Nagpur Airport",
    "Nhava Sheva Seaport",
    "Port Blair Airport",
    "Port Blair Seaport",
    "Pune Airport",
    "Raxaul Landport",
    "Rupaidiha Landport",
    "Surat Airport",
    "Tiruchirapalli Airport",
    "Trivandrum Airport",
    "Vallarpadam Seaport",
    "Varanasi Airport",
    "Vijayawada Airport",
    "Vishakhapatnam Airport",
    "Vishakhapatnam Seaport",
    "Vizhinjam International Seaport",
    "Vizhinjam Seaport"
]

# All Countries
COUNTRIES = [
    "AFGHANISTAN",
    "ALAND ISLANDS",
    "ALBANIA",
    "ALGERIA",
    "AMERICAN SAMOA",
    "ANDORRA",
    "ANGOLA",
    "ANGUILLA",
    "ANTARTICA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "ARUBA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA",
    "BOSNIA AND HERZEGOVINA",
    "BOTSWANA",
    "BOUVET ISLAND",
    "BRAZIL",
    "BRITISH INDIAN OCEAN TERRITORY",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "BURUNDI",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CAPE VERDE",
    "CARRIBEAN COMMUNITY",
    "CAYMAN ISLANDS",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHILE",
    "CHINA-CHINA",
    "CHINA- SAR HONGKONG",
    "CHINA- SAR MACAU",
    "CHRISTMAS ISLANDS",
    "COCOS (KEELING) ISLANDS",
    "COLOMBIA",
    "COMOROS",
    "CONGO",
    "CONGO (DEMOCRATIC REPUBLIC OF)",
    "COOK ISLANDS",
    "COSTA RICA",
    "COTE D'IVOIRE",
    "CROATIA",
    "CUBA",
    "CYPRUS",
    "CZECH REPUBLIC",
    "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    "DENMARK",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "EAST TIMOR (DEMOCRATIC REPUBLIC OF)",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESTONIA",
    "ESWATINI",
    "ETHIOPIA",
    "FALKLAND ISLANDS (MALVINES)",
    "FAROE ISLANDS",
    "FIJI",
    "FINLAND",
    "FRANCE",
    "FRANCE METROPOLITAN",
    "FRENCH GUIANA",
    "FRENCH POLYNESIA",
    "FRENCH SOUTHERN TERRITORIES",
    "GABON",
    "GAMBIA",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GIBRALTAR",
    "GREECE",
    "GREENLAND",
    "GRENADA",
    "GUADELOUPE",
    "GUAM",
    "GUATEMALA",
    "GUERNSEY",
    "GUINEA",
    "GUINEA-BISSAU",
    "GUYANA",
    "HAITI",
    "HEARD AND MCDONALD ISLANDS",
    "HONDURAS",
    "HUNGARY",
    "ICELAND",
    "INDIA",
    "INDONESIA",
    "IRAN",
    "IRAQ",
    "IRELAND",
    "ISLE OF MAN",
    "ISRAEL",
    "ITALY",
    "JAMAICA",
    "JAPAN",
    "JERSEY",
    "JORDAN",
    "KAZAKHSTAN",
    "KENYA",
    "KIRIBATI",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAOS",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LUXEMBOURG",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MARSHALL ISLANDS",
    "MARTINIQUE",
    "MAURITANIA",
    "MAURITIUS",
    "MAYOTTE",
    "MEXICO",
    "MICRONESIA (FEDERATED STATES OF)",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MONTENEGRO",
    "MONTSERRAT",
    "MOROCCO",
    "MOZAMBIQUE",
    "MYANMAR",
    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NETHERLANDS",
    "NETHERLANDS ANTILLES",
    "NEUTRAL ZONE",
    "NEW CALEDONIA",
    "NEW ZEALAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NIUE ISLAND",
    "NORFOLK ISLAND",
    "NORTHERN MARIANA ISLANDS",
    "NORWAY",
    "OMAN",
    "OTHERS",
    "PAKISTAN",
    "PALAU",
    "PALESTINE",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERSON OF UNSPECIFIED NATIONALITY",
    "PERU",
    "PHILIPPINES",
    "PITCAIRN",
    "POLAND",
    "PORTUGAL",
    "PUERTO RICO",
    "QATAR",
    "REFUGEE",
    "REFUGEE(NON-CONVENTIONAL)",
    "REPUBLIC OF KOREA",
    "REPUBLIC OF NORTH MACEDONIA",
    "REUNION",
    "ROMANIA",
    "RUSSIAN FEDERATION",
    "RWANDA",
    "SAINT HELENA",
    "SAINT KITTS AND NEVIS",
    "SAINT LUCIA",
    "SAINT PIERRE AND MIQUELON",
    "SAINT VINCENT AND THE GRENADINES",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPORE",
    "SLOVAKIA",
    "SLOVENIA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SOUTH AFRICA",
    "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS",
    "SOUTH SUDAN",
    "SOVEREIGN MILITARY ORDER OF MALTA",
    "SPAIN",
    "SRI LANKA",
    "STATELESS",
    "SUDAN",
    "SURINAME",
    "SVALBARD AND JAN MAYEN ISLANDS",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIAN ARAB REPUBLIC",
    "TAIWAN",
    "TAJIKISTAN",
    "TANZANIA",
    "THAILAND",
    "TIBET",
    "TOGO",
    "TOKELAU",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "TURKS AND CAICOS ISL",
    "TUVALU",
    "UGANDA",
    "UK BRITISH DEPENDENT TERRITORIES CITIZEN",
    "UK BRITISH NATIONAL(OVERSEES)",
    "UK BRITISH OVERSEES CITIZEN",
    "UK BRITISH PROTECTED PERSON",
    "UK BRITISH SUBJECT",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED KINGDOM",
    "UNITED NATIONS ORGANIZATION",
    "UNITED NATIONS SPECIALIZED AGENCY",
    "UNITED STATES MINOR OUTLYING ISLANDS",
    "UNITED STATES OF AMERICA",
    "URUGUAY",
    "UZBEKISTAN",
    "VANUATU",
    "VATICAN CITY STATE ( HOLY SEE)",
    "VENEZUELA",
    "VIETNAM",
    "VIRGIN ISLANDS (BRITISH)",
    "VIRGIN ISLANDS (US)",
    "WALLIS AND FUTUNA ISLANDS",
    "WESTERN SAHARA",
    "WEST SAMOA",
    "YEMEN",
    "ZAMBIA",
    "ZIMBABWE"
]

# Religion options
RELIGIONS = [
    "Bahai",
    "Buddhism",
    "Christian",
    "Hindu",
    "Islam",
    "Jainism",
    "Judaism",
    "Others",
    "Parsi",
    "Sikh",
    "Zoroastrian"
]

# Educational Qualifications
EDUCATIONAL_QUALIFICATIONS = [
    "Below Matriculation",
    "Graduate",
    "Higher Secondary",
    "Illiterate",
    "Matriculation",
    "NA Being Minor",
    "Others",
    "Post Graduate",
    "Professional"
]

# Visa Service Subtypes
TOURIST_SUBTYPES = [
    "Tourism, Recreation, Sight-seeing",
    "Meeting Friends/Relatives",
    "Short Term Yoga Program",
    "SHORT TERM COURSES ON LOCAL LANGUAGES, MUSIC, DANCE, ARTS & CRAFTS, COOKING, MEDICINE ETC. WHICH SHOULD NOT BE A FORMAL OR STRUCTURED COURSE/PROGRAMME (COURSES NOT EXCEEDING 6 MONTHS DURATION AND NOT ISSUED WITH A QUALIFYING CERTIFICATE/ DIPLOMA ETC).",
    "Voluntary Work of Short Duration"
]

BUSINESS_SUBTYPES = [
    "To Set Up Industrial/Business Venture",
    "Sale/Purchase/Trade",
    "Attend Technical/Business Meetings",
    "To Recruit Manpower",
    "Participation in Exhibitions, Business/Trade Fairs",
    "Expert/Specialist in Connection with an Ongoing Project",
    "Conducting Tours",
    "To Deliver Lecture(s) under Global Initiative for Academic Networks (GIAN)",
    "SPORTS RELATED ACTIVITY",
    "TO JOIN THE VESSEL"
]

CONFERENCE_SUBTYPES = [
    "TO ATTEND A CONFERENCE/SEMINAR/WORKSHOP ORGANIZED BY A MINISTRY OR DEPARTMENT OF THE GOVERNMENT OF INDIA,STATE GOVERNMENTS OR UT ADMINISTRATIONS AND THEIR SUBORDINATE/ ATTACHED ORGANIZATIONS AND PSUS AND PRIVATE CONFERENCES ORGANIZED BY PRIVATE PERSONS/COMPANIES/ORGANIZATIONS."
]

MEDICAL_ATTENDANT_SUBTYPES = [
    "TO ACCOMPANY PATIENT TRAVELLING TO INDIA ON EMEDICAL VISA"
]

TRANSIT_SUBTYPES = [
    "FOR SOLE PURPOSE OF ENABLING HIM/HER TRAVEL THROUGH INDIA TO A DESTINATION OUTSIDE INDIA."
]

# Country Phone Codes (sample - you may want to expand this)
COUNTRY_PHONE_CODES = [
    {"code": "+1", "country": "USA/Canada"},
    {"code": "+7", "country": "Russia"},
    {"code": "+20", "country": "Egypt"},
    {"code": "+27", "country": "South Africa"},
    {"code": "+30", "country": "Greece"},
    {"code": "+31", "country": "Netherlands"},
    {"code": "+32", "country": "Belgium"},
    {"code": "+33", "country": "France"},
    {"code": "+34", "country": "Spain"},
    {"code": "+36", "country": "Hungary"},
    {"code": "+39", "country": "Italy"},
    {"code": "+40", "country": "Romania"},
    {"code": "+41", "country": "Switzerland"},
    {"code": "+43", "country": "Austria"},
    {"code": "+44", "country": "UK"},
    {"code": "+45", "country": "Denmark"},
    {"code": "+46", "country": "Sweden"},
    {"code": "+47", "country": "Norway"},
    {"code": "+48", "country": "Poland"},
    {"code": "+49", "country": "Germany"},
    {"code": "+51", "country": "Peru"},
    {"code": "+52", "country": "Mexico"},
    {"code": "+53", "country": "Cuba"},
    {"code": "+54", "country": "Argentina"},
    {"code": "+55", "country": "Brazil"},
    {"code": "+56", "country": "Chile"},
    {"code": "+57", "country": "Colombia"},
    {"code": "+58", "country": "Venezuela"},
    {"code": "+60", "country": "Malaysia"},
    {"code": "+61", "country": "Australia"},
    {"code": "+62", "country": "Indonesia"},
    {"code": "+63", "country": "Philippines"},
    {"code": "+64", "country": "New Zealand"},
    {"code": "+65", "country": "Singapore"},
    {"code": "+66", "country": "Thailand"},
    {"code": "+81", "country": "Japan"},
    {"code": "+82", "country": "South Korea"},
    {"code": "+84", "country": "Vietnam"},
    {"code": "+86", "country": "China"},
    {"code": "+90", "country": "Turkey"},
    {"code": "+91", "country": "India"},
    {"code": "+92", "country": "Pakistan"},
    {"code": "+93", "country": "Afghanistan"},
    {"code": "+94", "country": "Sri Lanka"},
    {"code": "+95", "country": "Myanmar"},
    {"code": "+98", "country": "Iran"},
    {"code": "+212", "country": "Morocco"},
    {"code": "+213", "country": "Algeria"},
    {"code": "+216", "country": "Tunisia"},
    {"code": "+218", "country": "Libya"},
    {"code": "+220", "country": "Gambia"},
    {"code": "+221", "country": "Senegal"},
    {"code": "+222", "country": "Mauritania"},
    {"code": "+223", "country": "Mali"},
    {"code": "+224", "country": "Guinea"},
    {"code": "+225", "country": "Ivory Coast"},
    {"code": "+226", "country": "Burkina Faso"},
    {"code": "+227", "country": "Niger"},
    {"code": "+228", "country": "Togo"},
    {"code": "+229", "country": "Benin"},
    {"code": "+230", "country": "Mauritius"},
    {"code": "+231", "country": "Liberia"},
    {"code": "+232", "country": "Sierra Leone"},
    {"code": "+233", "country": "Ghana"},
    {"code": "+234", "country": "Nigeria"},
    {"code": "+235", "country": "Chad"},
    {"code": "+236", "country": "Central African Republic"},
    {"code": "+237", "country": "Cameroon"},
    {"code": "+238", "country": "Cape Verde"},
    {"code": "+239", "country": "Sao Tome and Principe"},
    {"code": "+240", "country": "Equatorial Guinea"},
    {"code": "+241", "country": "Gabon"},
    {"code": "+242", "country": "Congo"},
    {"code": "+243", "country": "DR Congo"},
    {"code": "+244", "country": "Angola"},
    {"code": "+245", "country": "Guinea-Bissau"},
    {"code": "+246", "country": "British Indian Ocean Territory"},
    {"code": "+248", "country": "Seychelles"},
    {"code": "+249", "country": "Sudan"},
    {"code": "+250", "country": "Rwanda"},
    {"code": "+251", "country": "Ethiopia"},
    {"code": "+252", "country": "Somalia"},
    {"code": "+253", "country": "Djibouti"},
    {"code": "+254", "country": "Kenya"},
    {"code": "+255", "country": "Tanzania"},
    {"code": "+256", "country": "Uganda"},
    {"code": "+257", "country": "Burundi"},
    {"code": "+258", "country": "Mozambique"},
    {"code": "+260", "country": "Zambia"},
    {"code": "+261", "country": "Madagascar"},
    {"code": "+262", "country": "Reunion"},
    {"code": "+263", "country": "Zimbabwe"},
    {"code": "+264", "country": "Namibia"},
    {"code": "+265", "country": "Malawi"},
    {"code": "+266", "country": "Lesotho"},
    {"code": "+267", "country": "Botswana"},
    {"code": "+268", "country": "Eswatini"},
    {"code": "+269", "country": "Comoros"},
    {"code": "+290", "country": "Saint Helena"},
    {"code": "+291", "country": "Eritrea"},
    {"code": "+297", "country": "Aruba"},
    {"code": "+298", "country": "Faroe Islands"},
    {"code": "+299", "country": "Greenland"},
    {"code": "+350", "country": "Gibraltar"},
    {"code": "+351", "country": "Portugal"},
    {"code": "+352", "country": "Luxembourg"},
    {"code": "+353", "country": "Ireland"},
    {"code": "+354", "country": "Iceland"},
    {"code": "+355", "country": "Albania"},
    {"code": "+356", "country": "Malta"},
    {"code": "+357", "country": "Cyprus"},
    {"code": "+358", "country": "Finland"},
    {"code": "+359", "country": "Bulgaria"},
    {"code": "+370", "country": "Lithuania"},
    {"code": "+371", "country": "Latvia"},
    {"code": "+372", "country": "Estonia"},
    {"code": "+373", "country": "Moldova"},
    {"code": "+374", "country": "Armenia"},
    {"code": "+375", "country": "Belarus"},
    {"code": "+376", "country": "Andorra"},
    {"code": "+377", "country": "Monaco"},
    {"code": "+378", "country": "San Marino"},
    {"code": "+380", "country": "Ukraine"},
    {"code": "+381", "country": "Serbia"},
    {"code": "+382", "country": "Montenegro"},
    {"code": "+383", "country": "Kosovo"},
    {"code": "+385", "country": "Croatia"},
    {"code": "+386", "country": "Slovenia"},
    {"code": "+387", "country": "Bosnia and Herzegovina"},
    {"code": "+389", "country": "North Macedonia"},
    {"code": "+420", "country": "Czech Republic"},
    {"code": "+421", "country": "Slovakia"},
    {"code": "+423", "country": "Liechtenstein"},
    {"code": "+500", "country": "Falkland Islands"},
    {"code": "+501", "country": "Belize"},
    {"code": "+502", "country": "Guatemala"},
    {"code": "+503", "country": "El Salvador"},
    {"code": "+504", "country": "Honduras"},
    {"code": "+505", "country": "Nicaragua"},
    {"code": "+506", "country": "Costa Rica"},
    {"code": "+507", "country": "Panama"},
    {"code": "+508", "country": "Saint Pierre and Miquelon"},
    {"code": "+509", "country": "Haiti"},
    {"code": "+590", "country": "Guadeloupe"},
    {"code": "+591", "country": "Bolivia"},
    {"code": "+592", "country": "Guyana"},
    {"code": "+593", "country": "Ecuador"},
    {"code": "+594", "country": "French Guiana"},
    {"code": "+595", "country": "Paraguay"},
    {"code": "+596", "country": "Martinique"},
    {"code": "+597", "country": "Suriname"},
    {"code": "+598", "country": "Uruguay"},
    {"code": "+599", "country": "Netherlands Antilles"},
    {"code": "+670", "country": "East Timor"},
    {"code": "+672", "country": "Antarctica"},
    {"code": "+673", "country": "Brunei"},
    {"code": "+674", "country": "Nauru"},
    {"code": "+675", "country": "Papua New Guinea"},
    {"code": "+676", "country": "Tonga"},
    {"code": "+677", "country": "Solomon Islands"},
    {"code": "+678", "country": "Vanuatu"},
    {"code": "+679", "country": "Fiji"},
    {"code": "+680", "country": "Palau"},
    {"code": "+681", "country": "Wallis and Futuna"},
    {"code": "+682", "country": "Cook Islands"},
    {"code": "+683", "country": "Niue"},
    {"code": "+685", "country": "Samoa"},
    {"code": "+686", "country": "Kiribati"},
    {"code": "+687", "country": "New Caledonia"},
    {"code": "+688", "country": "Tuvalu"},
    {"code": "+689", "country": "French Polynesia"},
    {"code": "+690", "country": "Tokelau"},
    {"code": "+691", "country": "Micronesia"},
    {"code": "+692", "country": "Marshall Islands"},
    {"code": "+850", "country": "North Korea"},
    {"code": "+852", "country": "Hong Kong"},
    {"code": "+853", "country": "Macau"},
    {"code": "+855", "country": "Cambodia"},
    {"code": "+856", "country": "Laos"},
    {"code": "+880", "country": "Bangladesh"},
    {"code": "+886", "country": "Taiwan"},
    {"code": "+960", "country": "Maldives"},
    {"code": "+961", "country": "Lebanon"},
    {"code": "+962", "country": "Jordan"},
    {"code": "+963", "country": "Syria"},
    {"code": "+964", "country": "Iraq"},
    {"code": "+965", "country": "Kuwait"},
    {"code": "+966", "country": "Saudi Arabia"},
    {"code": "+967", "country": "Yemen"},
    {"code": "+968", "country": "Oman"},
    {"code": "+970", "country": "Palestine"},
    {"code": "+971", "country": "UAE"},
    {"code": "+972", "country": "Israel"},
    {"code": "+973", "country": "Bahrain"},
    {"code": "+974", "country": "Qatar"},
    {"code": "+975", "country": "Bhutan"},
    {"code": "+976", "country": "Mongolia"},
    {"code": "+977", "country": "Nepal"},
    {"code": "+992", "country": "Tajikistan"},
    {"code": "+993", "country": "Turkmenistan"},
    {"code": "+994", "country": "Azerbaijan"},
    {"code": "+995", "country": "Georgia"},
    {"code": "+996", "country": "Kyrgyzstan"},
    {"code": "+998", "country": "Uzbekistan"}
]
